### ISSUE TITLE
bug in fmod

### ISSUE THREAD

**Issue by xhebox** [mauriciopoppe/interval-arithmetic#15]
Hi! Thx for your great work. I want to write a software like grafeq with js, but i have no time to clear all the detail of operation. And you saved my day, i have written a lib with decimal.js(MIT with your BSD).

And let's focus on the issue...When i test tri functions, i found fmod cant compute 5/5, or 3/3, i mean
```
 n = algebra.fmod(
  new Interval(2, 2),
  new Interval(2, 2)
)
Interval.almostEqual(n, [0, 0])

  1) interval operations algebra should compute the fmod:
     Error: expected 1.9999999999999998 to be close to 0
```

The problem is here:
```
rmath.intLo(rmath.divLo(x.lo, yb))
```
the same quantities give 1(2/2), divLo then rounded it to 0.9999, intLo then made it zero, and we got 1.999 at the end. I think there, we could just use raw math instead of round math.

**Comment by mauriciopoppe** [comment]
Thank you for the report and for the analysis that you've done, I also see that this is a bug in boost http://www.boost.org/doc/libs/1_66_0/boost/numeric/interval/arith2.hpp, I'm evaluating the suggestion of using raw math in this case

**Comment by mauriciopoppe** [comment]
fixed in https://github.com/mauriciopoppe/interval-arithmetic/releases/tag/v0.6.10

**Comment by xhebox** [comment]
wow, sweet, so fast
