### ISSUE TITLE
Case insensitive imports causing issue on *nix based systems

### ISSUE THREAD

**Issue by VolatilePulse** [mauriciopoppe/interval-arithmetic#17]
I know it's a long shot as this project hasn't had any commits in over 2 years, but as I'm currently developing on Windows and a *nix based system, I ran into an issue with this project. Many of your imports of `Interval` cause issues on the latter as files are case sensitive there. All imports (or requires) should match the case of the file, specifically `interval.js` would require all imports to be `interval` or similar. 

My current fix for this has been to modify the imports in each file to match the case of the file name, but this is less than ideal as the next time I install a package through npm, it will revert all of my changes.

**Comment by mauriciopoppe** [comment]
hey, I've rewritten the library with TypeScript a few months ago and I also remember doing something with the filename case, please try with the latest version, I haven't tried it on Windows so you should probably try it on a different workspace to avoid reverting the changes on your copy of the library.

**Comment by VolatilePulse** [comment]
I'm sorry, I should have clarified. The package available on npm does not have the case corrected yet. I do see that you have the correct case on GitHub, but it has not been pushed to npm yet. For the time being, I'll point npm here.

**Comment by mauriciopoppe** [comment]
thanks for letting me know about this, I uploaded a new version that has the case corrected, also the import has changed to this:

```javascript
const { Interval } = require('interval-arithmetic')
```

Fixed in https://github.com/mauriciopoppe/interval-arithmetic/tree/v1.0.1

**Comment by VolatilePulse** [comment]
I just tested it out on my main repo and everything appears to be working on my *nix system. Will double check on Windows before committing the change to master.

**Comment by VolatilePulse** [comment]
It looks like everything is working fine so far on the Windows system and the latest version has been added to my project. Thanks for the prompt response!
